### ISSUE TITLE
shellvars burp on newlines

### ISSUE THREAD

**Issue by briceburg** [jasmith590/COP#16]
I'm seeing `"": null` in output when parsing shellvars w/ newlines. 

```
[nesta@acorn ~]$ badevops-cop test.vars --yml
FOO: BAR
A: B
C: D
"": null
[nesta@acorn ~]$ cat test.vars  
FOO=BAR

A=B

# comment

C=D
```

**Comment by jasmith590** [comment]
Fixed and on develop, awaiting decision on new shell key|value pair issue

**Comment by briceburg** [comment]
:+1: thanks! I'm still playing w/ sample input, but think we're super close re #17
