### ISSUE TITLE
loading configuration from a subdirectory is broken

### ISSUE THREAD

**Issue by briceburg** [jasmith590/COP#24]
Loading configuration from a subdirectory only includes .yml files. If other files are present it either blows up or outputs  "unknown format ''"

```
#conf.d/a.yml
#conf.d/b.json
#conf.d/c.vars

$ bin/cop conf.d/
```

a.yml
```
---
a: "loaded"
```

b.json
```
{ "b": "loaded" }
```

c.vars
```
c=loaded
```

**Comment by jasmith590** [comment]
@briceburg should be fixed on the most recent develop [commit](https://github.com/jasmith590/COP/commit/fdebe47a6384a19b4640c7cd9d9027f3623d28db)
